In [12]:
import numpy as np

D = np.array( [[0.1,0.2,0.3],[0.3,0.4,0.5],[0.1,0.3,0.2],[0.6,0.7,0.8],[0.8,0.5,0.4],[0.9,0.1,0.2]] )

Dh = np.hstack((D, np.ones([6,1])))

print(D)
print(Dh)

[[0.1 0.2 0.3]
 [0.3 0.4 0.5]
 [0.1 0.3 0.2]
 [0.6 0.7 0.8]
 [0.8 0.5 0.4]
 [0.9 0.1 0.2]]
[[0.1 0.2 0.3 1. ]
 [0.3 0.4 0.5 1. ]
 [0.1 0.3 0.2 1. ]
 [0.6 0.7 0.8 1. ]
 [0.8 0.5 0.4 1. ]
 [0.9 0.1 0.2 1. ]]


In [15]:

t = np.identity(4)
t[:,3] = [-0.5,0.5,0.1,1]
print(t)

t@Dh.T

[[ 1.   0.   0.  -0.5]
 [ 0.   1.   0.   0.5]
 [ 0.   0.   1.   0.1]
 [ 0.   0.   0.   1. ]]


array([[-0.4, -0.2, -0.4,  0.1,  0.3,  0.4],
       [ 0.7,  0.9,  0.8,  1.2,  1. ,  0.6],
       [ 0.4,  0.6,  0.3,  0.9,  0.5,  0.3],
       [ 1. ,  1. ,  1. ,  1. ,  1. ,  1. ]])

In [46]:
S = np.identity(4)
row, col = np.diag_indices_from(S)
S[row,col] = np.array([3, 2, 4, 1])
print(S)

[[3. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 4. 0.]
 [0. 0. 0. 1.]]


In [71]:
min_i = D.min(axis = 0)
mx_i = D.max(axis = 0)
T = np.identity(4)
T[:3,3] = -min_i
print(T)

scale = 1/(mx_i-min_i)
print(scale)
S = np.identity(4)
row, col = np.diag_indices_from(S)
S[row,col] = np.append(scale,1)
print(S)
result = S@T@Dh.T
print(result.T)

[[ 1.   0.   0.  -0.1]
 [ 0.   1.   0.  -0.1]
 [ 0.   0.   1.  -0.2]
 [ 0.   0.   0.   1. ]]
[1.25       1.66666667 1.66666667]
[[1.25       0.         0.         0.        ]
 [0.         1.66666667 0.         0.        ]
 [0.         0.         1.66666667 0.        ]
 [0.         0.         0.         1.        ]]
[[0.         0.16666667 0.16666667 1.        ]
 [0.25       0.5        0.5        1.        ]
 [0.         0.33333333 0.         1.        ]
 [0.625      1.         1.         1.        ]
 [0.875      0.66666667 0.33333333 1.        ]
 [1.         0.         0.         1.        ]]


In [55]:
mins = D.min(axis = 0)
T[:3,3] = -mins
print(T)
S = np.eye(4)
maxes = D.max(axis = 0)
print("maxes",maxes)
scale = 1/(maxes-mins)
print("scale", scale)
row, col = np.diag_indices_from(S)

S[row,col] = np.append(scale,1)
print("scaling matrix:", S)

result = S@T@Dh.T
result = result[:D.shape[1],:]
result = result.T
print (result)

[[ 1.   0.   0.  -0.1]
 [ 0.   1.   0.  -0.1]
 [ 0.   0.   1.  -0.2]
 [ 0.   0.   0.   1. ]]
maxes [0.9 0.7 0.8]
scale [1.25       1.66666667 1.66666667]
scaling matrix: [[1.25       0.         0.         0.        ]
 [0.         1.66666667 0.         0.        ]
 [0.         0.         1.66666667 0.        ]
 [0.         0.         0.         1.        ]]
[[0.         0.16666667 0.16666667]
 [0.25       0.5        0.5       ]
 [0.         0.33333333 0.        ]
 [0.625      1.         1.        ]
 [0.875      0.66666667 0.33333333]
 [1.         0.         0.        ]]
