# Numpy Tutorial

Oliver W. Layton and Stephanie R Taylor

CS251: Data Analysis and Visualization

Spring 2021

In [5]:
import numpy as np

In [115]:
cow = np.array( [ [1.1,2.2,3.3], [2.1,4.2,6.2], [3.1,6.2,9.3], [4.1,8.2,12.3] ] )
print(cow.shape)
socks = np.mean(cow,axis=0)
print(socks.shape)
coat = cow.std(axis = 0)
print(coat.shape)
zed = (cow - socks) / coat
print(zed.shape)
trend = np.mean( cow, axis=1 )
print(trend.shape)
whatsit = np.mean( cow )
print(whatsit.shape)
print(whatsit)

(4, 3)
(3,)
(3,)
(4, 3)
(4,)
()
5.191666666666666


In [96]:
tree = np.random.random( (6,5,7) )#6個5row*7col
print(tree)
shrub = tree.mean(axis = 0)
print(shrub.shape)# not really sure why it does this. (5,7)
# is it because it summarises it across all columns? 
# so the 6 items converge into one number?

trimmed = tree - tree.mean(axis = 0)
print(trimmed.shape) #mean across the columns (5,7)
bush = tree.mean(axis = 2)
print(bush.shape) # mean across the 6 items (6,5), calculating the rows?
shears = tree.mean(axis = 1) #mean across the 6 items, calculating the rows (6,7)
print(shears.shape)



[[[0.19513866 0.20720215 0.94741952 0.86464084 0.61605405 0.84140724
   0.20969214]
  [0.87402882 0.86730751 0.24811225 0.50837331 0.92977426 0.67915
   0.66051911]
  [0.5597646  0.26883156 0.97841537 0.44750965 0.3114501  0.72858071
   0.60770481]
  [0.34224131 0.30379159 0.21450669 0.07848644 0.62571091 0.50569364
   0.23484841]
  [0.05512453 0.01890107 0.73849593 0.18825319 0.26664362 0.01411219
   0.15063905]]

 [[0.87444572 0.24206083 0.9539582  0.16434684 0.25326146 0.86770997
   0.42660834]
  [0.26782894 0.69281376 0.0512284  0.89060518 0.84156155 0.08579704
   0.79861875]
  [0.96117044 0.49206962 0.56815335 0.67979674 0.26672694 0.64966126
   0.4748675 ]
  [0.4055418  0.90280156 0.79790311 0.93460763 0.83665182 0.0418106
   0.60652939]
  [0.69763688 0.66485748 0.27195643 0.42563035 0.03902914 0.09409413
   0.5605119 ]]

 [[0.58241176 0.20122929 0.44820272 0.47207726 0.01133678 0.14252078
   0.62430006]
  [0.99282011 0.65039175 0.12021667 0.8214403  0.43153772 0.08370021
   0.59

In [134]:
trimmed = tree-shears.reshape(6,1,7)
print(trimmed.shape)

(6, 5, 7)


## Numpy ndarray basics

### Creation from Python lists

In [6]:
# Make a numpy array from a 2D python list

pl = [[1,2,3],[4,5,6]]
arr = np.array(pl)
print(pl)
print(arr)

#prnt the four
print(pl[1][0])
print(arr[1,0])

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
4
4


In [7]:
# print it


### Data type of ndarray

In [8]:
# determine data type
print('Type of array is\n')

Type of array is



Type can be set or changed in a few ways. 

1. when creating array — (a) implicitly or (b) explicitly
2. by casting types.

In [9]:
# 1a implicitly (from input literals)
arr = np.array()

TypeError: array() missing required argument 'object' (pos 0)

In [ ]:
# 1b explicitly


In [14]:
# 2. NOTE: Casting is a METHOD of the array, not a FUNCTION
arr = arr.astype(np.float64)
print(arr)
print(arr.dtype)

[  5. 234.]
float64


In [13]:
# Can also be string. be careful in your CSV parser that your "numbers"
# aren't actually strings!
arr = np.array(["5.0","234"])
print(arr.dtype)
#help(arr)
arr = np.array(["5.0","234"],np.float64)
print(arr.dtype)

<U3
float64


### Convert back to Python list

In [15]:
# Convert back from ndarray to Python list (2 methods)
the_list = arr.tolist()
print(type(the_list))

<class 'list'>


### Other ways to create ndarrays quickly

#### 1. zeros
1D (N,) tuple of length 1

2D (N,M) tuple of length 2 

3D (N,_____M,______L) 

  no. of elemnts, np. of elements in 1st dim, no. elements in 2nd dimension
   

In [16]:
arr = np.zeros( (4,))
print(arr)
print(arr.shape)

arr = np.zeros((2,3,4))
print(arr)

[0. 0. 0. 0.]
(4,)
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


#### 2. ones

In [17]:
arr = np.ones((6,4))
print(arr)
print(arr.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(6, 4)


In [21]:
# can easily make any constant array
arr = 5* np.ones((6,4))
print(arr)

arr = 5 + np.zeros((6,4))
print(arr)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


#### 3. Random values

In [76]:
# Uniform random values

#old way
np.random.seed(0) # If I don't put seed, everytime I rerun, the number is different. 
print(np.random.random([5,4]))
# print(np.random.random([5,4])) 

# #new way (preferred by Numpy developers)
# rng = np.random.default_rng(seed = 0)
# print(rng.random((5,4)))
# print(rng.random((5,4)))

[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]
 [0.0202184  0.83261985 0.77815675 0.87001215]]


#### 4. Equally spaced floats in an interval

In [40]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

#### 5. Equally spaced ints in an interval

In [52]:
print(np.arange(10)) # 0......9
print(np.arange(0,10,2)) #0....9 but with only even numbers

print(np.arange(0,10,2)) #0....9 but with only even numbers

print(np.arange(0,9.5,0.5)) # 0 to 9 with a step of 0.5

print(np.linspace(0,10,11)) # the last part if the number of steps

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 2 4 6 8]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9. ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


### Check dimensions — `shape`

In [54]:
# check shape of 3D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)


(2, 3)


In [ ]:
# check number of dimensions (M)


In [ ]:
# Access 1st dim (#rows), 2nd dim (#cols) (Use f-string)


In [ ]:
# Check number of elements total


## Brief detour: Rapidly build python lists (list comprehension)

In [ ]:
# Brief detour: In python you can replace the workflow of 
# list-building by creating an empty list and looping to append...


In [ ]:
# ...with Python list comprehensions


In [ ]:
# you can build lists using any function of i. How about i^2?


## ndarray indexing

Basic Accessing and modifying of ndarrays.

### Access and modify single elements

In [66]:
# To access elements in a multidimensional ndarray use ONE set of square brackets []
# Make a new random array
np.random.seed(0)  # ensures random numbers come up the same each time. Useful for debugging.

arr = np.random.random((3,5))
print(arr)

[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]]


In [67]:
# Get the 1st element

print(arr[0,0])

0.5488135039273248


In [68]:
# Modifying single values is similar

print('arr is now:\n', arr)

arr is now:
 [[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]]


### Slicing: real power of numpy

Use **colon** notation for all values in a dimension

Access and modify different ranges of data along different dimensions 

Make a 3x5 random array. Access 2nd column

In [69]:
np.random.seed(0)
row_idx = 1 #2nd row
col_idx = 0 #first column
print(arr[row_idx,col_idx])
arr[row_idx,col_idx] = 7
print('arr is now:\n', arr)

0.6458941130666561
arr is now:
 [[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [7.         0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]]


Access 1st row

In [70]:
print(arr[0,:])

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


Access last 2 columns

In [71]:
print(arr[:,-2:])
print(arr[:,3:])

[[0.54488318 0.4236548 ]
 [0.96366276 0.38344152]
 [0.92559664 0.07103606]]
[[0.54488318 0.4236548 ]
 [0.96366276 0.38344152]
 [0.92559664 0.07103606]]


Access columns at indices 1-2 and in 1st row. Careful about off-by-one.

- Low range (before :) CONTAINS that index
- High range (after :) DOES NOT contain that index (i-1)

In [72]:
arr = np.array([1,2,3,4,5,6])
print(arr[::2])

[1 3 5]


Use slicing to assign values efficiently in batch without loops

In [ ]:
# Assign 1st row to -1s


In [ ]:
# Assign 1st row to increasing ints


In [ ]:
# Multiply the 3rd row by 5 times itself and update the row


### What if we want to access a set of rows or columns that are not adjacent?

Can't use colon notation. Instead use `np._ix`

Example: Say we want column indices 0, 2, 4 and all rows.

**Syntax for `np._ix`:**
- `np._ix` goes inside the square brackets: `arr[np._ix(blah)]`
- Give it `M` arguments (e.g. 2 for a 2D matrix).
- Each argument is a Python list (or ndarray) of indices to take along that dimension.

## Memory

- Numpy tries to be efficient with arrays so assignment does a shallow copy. To do a deep copy, you need to use `.copy()` method

In [ ]:
a = np.linspace(-1, 1, 5)
a

In [ ]:
# fixed with .copy()

## Reshaping

**Problem:**
- You want to preserve the number of elements in an ndarray but "regroup" the elements

Example: Have a `64 x 64` image and want to make one big `64*64` 1D vector by "gluing the rows together":

e.g: (3, 3) -> (9,)

Turn:

    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

Into:

     [1, 2, 3, 4, 5, 6, 7, 8, 9]

How can we do this without hard coding?

**Key:** Total number of elements in ndarray doesn't change.

## Combining multiple ndarrays

**Problem:**
- You have two ndarrays and want to concatenate them
- You have an ndarray and **want to append a column or row vector**

### Add/append a new column — "stack horizontally"

**Mnemonic**: Columns go horizontally.

Have `a`:

    [[1, 2]
     [3, 4]]
and `b`

    [[9]
     [9]]
    
want to make:

    [[1, 2, 9]
     [3, 4, 9]]
    
i.e. stack horizontally. Could be two matrices (not just a matrix and a vector).

**Caveat:** We need to make sure shapes are compatible for broadcasting:

- Result shape = `(2, 3)`
- We are starting with `a` shape: `(2, 2)`

The shape of `b` needs to be `(2, 1)` (why wouldn't `(1, 2)` work?)

## Math with ndarrays (vectorization)
There are many options for doing math with ndarrays. If we can apply a function to an entire array or have an entire array as an operand in a mathematical operation (which we can), then we call this **Vectorization** and we avoid loops.

First, we talk about functions. Then, we talk about mathematical expressions.

## Built-in functions that compute along dimensions (`axes`)

- Axes are the numpy term for different ndarray dimensions. 
- Example: axis 0 are the rows, axis 1 are the columns, etc.
- We can apply functions over one or more axis super efficiently in one line of code! This is MUCH MUCH faster than loops (stay tuned).

Sum along rows -> "collapse" across rows to get sum within each column — 5 numbers

Sum along columns -> "collapse" across columns to get sum within each row — 3 numbers

**Careful:** Applying a function without specifying the axis may compute across the ENTIRE ndarray.

**Mnemonic trick:** Applying a function along an axis eliminates that dimension from the shape. Left with remaining dimensions.

In [ ]:
print(one.shape)

print(f'Mean across axis 0: {the_mean.shape}')

print(one.shape)

print(f'Mean across axis 1: {the_mean.shape}')

## Math Operations with ndarrays
In NumPy, you can apply the same operations as with scalars (+,-,\*,/,\**), but to every element of an ndarray. This is super straightforward if the operands are ndarrays with the same shape. Then the operations are simply performed element-wise.

But what if the operands are not identically sized? Under certain conditions, NumPy will do the work (hopefully the work you want) anyways. NumPy does this via a powerful feature called Broadcasting.

## Broadcasting

**This is the most useful numpy feature thus far! This will become your bread-and-butter!**

### Simple example: A Scalar and an NDarray

As we saw, we can create an array of any size with any constant value WITHOUT ANY LOOPS. This is the simplest example of numpy **broadcasting** the scalar across the ndarray.

In [ ]:
# Example with basic arithmetic


### Example: Subtract the minimum value of each column for the original 2D array
In this case, we have a 2D array and a 1D array. 

In [ ]:
np.random.seed(0)
rand_inds = np.random.randint(low=0, high=5, size=(5, 6))
rand_inds

In [ ]:
# Take the min across each column and subtract it from rand_inds. Print shape of result

print(result.shape)

#### What's going on??

Let's look at the shapes:

Numpy is **broadcasting** the vector to operate on the 2d ndarray (**draw this out on board**):

- Numpy looks for axis shape compatibility among the different arrays.
- Numpy sees the column dimension (5, **6**) matches the min vector (**6,**)
- Numpy adds a **singleton dimension** (a "fake" leading dimension for rows). Now the min vector is treated with shape: **(1, 6)**.
- Numpy dynamically "grows" the singleton dimension to the needed shape (5). So now the min vector is treated like a (5, 6) array.
- Numpy element-wise subtracts the two arrays: (5, 6) array can be subtracted by a (5, 6) array.
- Numpy returns the result, which is a (5, 6) array!

Process is **very memory efficient**: No new memory gets allocated during broadcasting.

#### Broadcasting only adds singleton dimensions LEFTWARD to the ndarray with smaller number of dimensions.

What if we did the same thing as above, but now wanted to **subtract the minimum value in each row**?

In [ ]:
print(f'rand_inds shape: {rand_inds.shape}')
print(f'min shape: {np.min(rand_inds, axis=1).shape}')

**Problem:** adding singleton dimensions to the LEFT could never make the shapes compatible!! For example, numpy tries: 

    rand_inds shape: (5, 6)
    min shape: (1, 5)

but that won't work! Crash...

#### Adding singleton dimensions by ourselves

We can help numpy out and add a "new axis" ourselves to make the shapes compatible with `np.newaxis`!

Can also make this more readable by defining a temp variable...

#### Squeeze if you need to get rid of all singleton dimensions

"Undo" a new axis / singleton dimension

In [ ]:
ex = np.zeros([1, 2, 1, 3, 1, 4, 5, 1])
ex.shape

#### Not automatically squeezing computations

As we saw above, functions like `min` over an axis eliminate that axis from the result: 

In [ ]:
print(f'Min over axis 0 shape: {.shape}')
print(f'Min over axis 1 shape: {.shape}')

If we want `min` (and some other functions) to keep the singleton dimension, we can use the optional argument `keepdims=True`:

In [ ]:
print(f'Min over axis 0 shape: {.shape}')
print(f'Min over axis 1 shape: {.shape}')

This can **help with broadcasting compatibility when performing an operation on an axis then modifying the original ndarray.** Then we don't need to manually add a new axis.

Example with subtracting the mean:

In [ ]:
# Subtract off mean along either axis
rand_inds_centered = rand_inds.copy()

## Vectorization speed vs loops

Time computation of adding 1 to a ndarray with loop vs vectorized.

In [ ]:
def timeit(fun):
    '''Just a function to time the runtime of another function'''
    def timer():
        start = time.time()
        fun()
        end = time.time()
        print(f'Took {end - start:.3} secs to run.')
    return timer


@timeit
def sumLoop():
    '''Use for loop to sum a row vector'''
    longRow = np.array([i for i in range(1, 1000000)])
    theSum = 0
    for i in range(len(longRow)):
        theSum += longRow[i]


@timeit
def sumVectorized():
    '''Vectorized version of summing a row vector'''
    longRow = np.array([i for i in range(1, 1000000)])
    theSum = np.sum(longRow)

In [ ]:
# Dynamic typing in python makes for loops with lots of small
# operations slow
print('addOneLoop:')
addOneLoop()

# Vectorization allows Numpy to stop searching at runtime
# and use efficient pre-compiled functions to batch-process
# the computation over the matrix
print('addOneVectorized:')
addOneVectorized()